name: CustomFeed
main: CustomFeed\Main
version: 1.0.0
api: 3.0.0, 4.0.0
commands:
  feed:
    description: Set hunger to full
      usage: /feed
        permission: valion.feed

author: xZolpha
