name: CustomFeed
main: CustomFeed\Main
version: 1.0.0
api: 3.0.0, 4.0.0
commands:
  feed:
    description: Have yourself full hunger!
      usage: /feed
        permission: server.feed

author: xZolpha
